# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Racca.me
    url: https://racca.me
  - name: Blog
    url: https://racca.me

status-website:
  cname: upptime.racca.me
  name: Upptime - racca.me
  introTitle: "[**racca.me**](https://racca.me)'s upptime status page powered by [Upptime](https://github.com/upptime/upptime)."
  introMessage: This page contains **real-time** data from [racca.me](https://racca.me)'s websites
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
