owner: SebaOfficial
repo: upptime

sites:
  - name: Racca.me
    url: https://racca.me
    icon: https://racca.me/favicon.ico
  - name: Blog
    url: https://racca.me
    icon: https://blog.racca.me/favicon.ico
  - name: TelegramSDK
    url: https://botapi.racca.me
    icon: https://botapi.racca.me/favicon.ico
  - name: QWER
    url: https://qwer.racca.me
    icon: https://qwer.racca.me/favicon.ico

status-website:
  cname: upptime.racca.me
  name: Upptime | racca.me
  logoUrl: https://racca.me/assets/img/avatar.png
  favicon: https://racca.me/favicon.ico
  introTitle: "[**racca.me**](https://racca.me)'s upptime status page powered by [Upptime](https://github.com/upptime/upptime)."
  introMessage: This page contains **real-time** data from [racca.me](https://racca.me)'s websites
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  js: "<!-- Cloudflare Web Analytics --><script defer src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{\"token\": \"a26b652fb59e471fab055eb0cfbb5681\"}'></script><!-- End Cloudflare Web Analytics -->"